---
- name: get bareos pass
  command: >
    awk '/Password/ {print $3}' /etc/bareos/bareos-fd.d/director/bareos-dir.conf
  register: bpass

- name: create client config bareos 17.x/19.x
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: bareos
    group: bareos
    mode: '0640'
  with_items:
    - { src: 'templates/bareos-dir.conf.j2', dest: '/etc/bareos/bareos-fd.d/director/bareos-dir.conf' }
    - { src: 'templates/myself.conf.j2', dest: '/etc/bareos/bareos-fd.d/client/myself.conf' }
  notify: Restart Bareos Client

- name: enable bareos-fd service in boot
  systemd:
    name: bareos-fd
    enabled: yes

- name: Start bareos-fd service
  systemd:
    state: started
    name: bareos-fd

- name: identifying service hosted in server
  shell: >
    ps axo user | grep -m 1 "^tomcat\|^jboss" || pgrep -xl "apache2|httpd|mysqld|postgres" | cut -d" " -f 2 | tail -n1
  register: service

